# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6d276b7c5afd2d65e8b4bdea426b8e4ee5c7f6e30a98875607de086af31e34900dba1efc5b6fe6365e464838dc9ca31baee63e2f12fe7f6b4a6d5c9970a7b3

test:
  secret_key_base: 7508fca2b3ca322a78b3c4b684bcb98c1b99e89b504a84857e908cfcbe033821041878004da1d985c6b11efe6144e4ce572f32a1744f7ea5761d4ee068f8926b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
