# config/secrets.yml
defaults: &defaults
  secret_key_base: '6e6d276b7c5afd2d65e8b4bdea426b8e4ee5c7f6e30a98875607de086af31e34900dba1efc5b6fe6365e464838dc9ca31baee63e2f12fe7f6b4a6d5c9970a7b3'
  devise_secret_key: 'ef7d29691e7ea51fd0439cb054cfa4926467f648b25ed49a569dc918d661dd8e1008dbf66f2ab18463046edfbb04573b633c5d3990ea3aecf8087c63bde725f2'
  devise_pepper: '4884116ac4787886fe6e235d8a21f47f365d500804bf29ef07f06a9ca7e120434e70170915452a70294f2f4f22b332c4286a9b2517fe8282937109a57c4336bc'
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_region: <%= ENV['S3_REGION'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  email_addresses: &email_addresses
    noreply: Taggit <jayshree@streamoid.com>
    alerts: Taggit <jayshree@streamoid.com>

secured: &secured
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  fog_region: <%= ENV['FOG_REGION'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured
